# templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-helm-repo.fullname" . }}
  labels:
    app: {{ include "my-helm-repo.name" . }}
    chart: {{ include "my-helm-repo.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: {{ include "my-helm-repo.name" . }}
